ism_url = "localhost"
ism_port= 5403
log_level = "debug"
cors_origin = "http://localhost:4200"
use_kafka = true
push_notification_access_token="oiqhfriuhf"
push_notification_url="http://localhost:4200"

[message_db_config]
db_url = "localhost:9042"
db_user = "cassandra"
db_password = "cassandra"
db_keyspace = "messaging"
with_db_init = true

[user_db_config]
db_host = "localhost"
db_port = "32768"
db_user = "postgres"
db_password = "meventure1234"
db_name = "postgres"

[token_issuer]
iss_host = "http://localhost:8180/"
iss_realm = "meventure"

[object_db_config]
access_key = "minioadmin"
storage_url = "http://localhost:9000"
secret_key = "minioadmin"
bucket_name = "mv-rooms"

[kafka_config]
bootstrap_host = "localhost"
bootstrap_port = 19092
topic = "push-notifications.requested.v1"
client_id = "ism-1"
partition = [0]
consumer_group = "ism"